#!/bin/bash


#Necesary libraries for GSI
export NETCDF=/usr/local/
export LAPACK_PATH=/home/jruiz/share/lapack/2.5.4/gcc/

#Variables associated to the compiler
export FC=mpif90
export CXX=mpicxx
export CC=mpicc
export F90=mpif90

#Create folder to build the system
rm -fr ./build
mkdir -p build
cd build

cmake -VERBOSE=1 ../  -DBUILD_WRF=ON #By defaout ENKF uses the GFS option instead of WRF.
make
